version: '3'
services:
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./app:/basket/app
    depends_on:
        - api
  api:
    build: backend
    ports:
      - "4567:4567"
    environment:
      - HOST=0.0.0.0
      - PORT=4567
